config/routes.rb
Rails.application.routes.draw do
  resources :search_suggestions
  resources :orders do
    member do
      get 'delete_cart_product'
    end
  end
  post 'orders/put_quantity', to: 'orders#put_quantity'

  devise_for :admin_users, ActiveAdmin::Devise.config
  resources :reviews
  ActiveAdmin.routes(self)
  resources :feature_values
  resources :features
  root to: 'products#index'
  resources :categories
  resources :products do
    member do
      post 'add_to_cart'
    end
  end
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_products, dependent: :destroy
  enum status_keys: {
      'Processing' => 0,
      'Shipped' => 1,
      'Received' => 2
  }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
            format: { with: VALID_EMAIL_REGEX }
  validates :name, presence: true, length: { maximum: 40 }
  validates :phone, presence: true, length: { maximum: 11 }

  def place(products, order_id)
    products = eval(products)
    products.each do |p|
      OrderProduct.create(product_id: p[:product_id], order_id: order_id,
                          actual_price: Product.find(p[:product_id]).price, quantity: p[:quantity])
    end
  end

  def total_price(order)
    @price = 0
    OrderProduct.where(order_id: order.id).each do |f|
      @price += f.actual_price * f.quantity
    end
    @price
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  def index
  end

  def new
    @order = Order.new
  end

  def create
    @order = Order.create(order_params)
    respond_to do |format|
      if @order.save
        format.html do
          products = cookies[:cart]
          @order.place(products, @order.id)
          AdminMailer.order_confirmation(@order).deliver
          CustomerMailer.order_confirmation(@order).deliver
          cookies.delete :cart
          redirect_to root_url,
                      flash:  {notice: "Order created, wait for email"}
        end
      else
        format.html  { render :new }
      end
    end
  end

  def destroy
  end

  def delete_cart_product
    product_id = params[:id]
    products = eval(cookies[:cart])
    products.delete_if { |h| h[:product_id] == product_id }
    cookies[:cart] = products.to_s
    redirect_to :back
  end

  def put_quantity
    products = eval(cookies[:cart])
    products.each do |p|
      q = "quantitys_#{p[:product_id]}".to_sym
      qty = params[:quantity][q][:qty]
      p[:quantity] = qty
    end
    cookies[:cart] = products.to_s
    redirect_to new_order_path
  end


  private

  def order_params
    params.require(:order).permit(:name, :phone,
                                  :email, :status)
  end

end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/index.html.erb
<% if cookies[:cart].present? && !eval(cookies[:cart]).length.zero? %>
    <div class="table-orders col-md-9 ">
      <div class="table-orders col-md-12 ">
      <div class="order-div photo">Photo</div>
      <div class="order-div title"> Title</div>
      <div class="order-div price">Price</div>
      <div class="order-div quantity">Quantity</div>
      </div>
      <hr>
    <%= form_for :quantity , url: {action: "put_quantity"} do |f| %>
        <% eval(cookies[:cart]).each do |obj| %>
            <div class="table-order col-md-12">
            <% @product = Product.find(obj[:product_id]) %>
            <div class="order-div">
              <div><%= image_tag @product.photo_url(:thumb) %></div>
            </div>
            <div class="order-div title">
              <p><%= @product.title %></p>
            </div>
            <div class="order-div price" data-value="<%= @product.price %>">
              <p><%= number_to_currency(@product.price) %></p>
            </div>
            <div class="order-div quantity">
              <%= f.fields_for "quantitys_#{obj[:product_id]}" do |p| %>
                <div><%= p.number_field :qty, value: 1 , min: 1 %></div>
              <% end %>
            </div>
            <div class="order-div delete">
              <%= link_to 'Delete product', delete_cart_product_order_path(@product), class: 'button' %>
            </div>
            </div>
        <% end %>
        <%= f.submit 'Create Order', class:'submit-products' %>
    <% end %>
    </div>
    <div><h4>Total price : $<span id="totalprice"></span></h4></div>
<% else %>
    <h2>No products in the cart</h2>
<% end %>

app/views/orders/new.html.erb
<div class="col-md-9">
  <%= form_for(@order)  do|f| %>
      <% if @order.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@order.errors.count, "error") %> prohibited this order from being created:</h2>

            <ul>
              <% @order.errors.full_messages.each do |message| %>
                  <li class="order_error_message"><%= message %></li>
              <% end %>
            </ul>
          </div>
      <% end %>

      <div class="field form-group">
        <%= f.label :name, "Name:" %>
        <%= f.text_field :name, class: "form-control form-width" %>
      </div>

      <div class="field form-group">
        <%= f.label :phone, "Your phone:"%>
        <%= f.number_field :phone, class: "form-control form-width"%>
      </div>

      <div class="field form-group">
        <%= f.label :email, "Your Email"%>
        <%= f.text_field :email, class: "form-control form-width"%>
      </div>

      <div class="actions button-margin">
        <%= f.submit "Appy" , class: "btn btn-success" %>
      </div>
  <% end %>
</div>