config/routes.rb
Rails.application.routes.draw do
  resources :search_suggestions
  resources :orders do
    member do
      get 'delete_cart_product'
    end
  end
  post 'orders/put_quantity', to: 'orders#put_quantity'

  devise_for :admin_users, ActiveAdmin::Devise.config
  resources :reviews
  ActiveAdmin.routes(self)
  resources :feature_values
  resources :features
  root to: 'products#index'
  resources :categories
  resources :products do
    member do
      post 'add_to_cart'
    end
  end
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  has_many :feature_values, dependent: :destroy
  accepts_nested_attributes_for :feature_values, allow_destroy: true
  has_many :features, through: :feature_values
  has_many :reviews, dependent: :destroy
  has_many :related_products
  accepts_nested_attributes_for :related_products, allow_destroy: true
  has_many :related_products_associated, class_name: 'RelatedProduct', foreign_key: 'associated_id'
  has_many :order_products


  validates :title, presence: true, uniqueness: true, length: { maximum: 80 }
  validates :price, presence: true
  validates :photo, presence: true

  scope :by_created, -> { order("created_at DESC") }

  mount_uploader :photo, ProductPhotoUploader
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product,  only: [:show, :edit, :update, :destroy]
  require 'will_paginate/array'
  def index
    if params[:search]
     @products = Product.where('title LIKE ?', "%#{params[:search]}%").by_created.page(params[:page]).per_page(9)
    else
     @products = Product.all.by_created.page(params[:page]).per_page(9)
    end
  end

  def show
    @product_ass = association
    @product_ass = @product_ass.paginate(page: params[:page], per_page: 4 )
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.create(product_params)
    redirect_to @product
  end

  def edit
  end

  def update
    @product.update(product_params)
    redirect_to product_path
  end

  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to root_url }
      format.json { head :no_content }
    end
  end

  def add_to_cart
    product_id = params[:id]
     if cookies[:cart].present?
       products = eval(cookies[:cart])
       if !products.include?({ product_id: product_id, quantity: 1 })
         product = { product_id: product_id, quantity: 1 }
         products << product
         cookies[:cart] = products.to_s
       end
     else
      cookies[:cart] = [{ product_id: product_id, quantity: 1 }].to_s
     end
    redirect_to :back
  end

  private

  def set_product
    @product = Product.find(params[:id])
  end

  def product_params
    params.require(:product).permit(:title, :price,
                                    :photo, :description,
                                    :in_stock, :category_id)
  end

  def association
    product_as = []
    @product = Product.find(params[:id])
    @product.related_products.each do |t|
      product_as << t.associated
    end
    @product.related_products_associated.each do |t|
      product_as << t.product
    end
    product_as
  end

end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_desctiption.html.erb
<table>
  <tr><th><%= @product.description %></th></tr>
</table>

app/views/products/_feature.html.erb
<tr>
  <th><%=  @feature.feature.title %></th>
  <th><%=  @feature.title %></th>
</tr>

app/views/products/_form.html.erb
<div class="col-md-9">
  <%= form_for(@product)  do|f| %>
      <% if @product.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

            <ul>
              <% @product.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
              <% end %>
            </ul>
          </div>
      <% end %>

      <div class="field form-group">
        <%= f.label :title, "Name:" %>
        <%= f.text_field :title, class: "form-control form-width" %>
      </div>

      <div class="field form-group">
        <%= f.label :price, "price:"%>
        <%= f.text_field :price, class: "form-control form-width"%>
      </div>

      <div class="field form-group">
        <%= f.label :category_id, "category_id"%>
        <%= f.text_field :category_id, class: "form-control form-width"%>
      </div>

      <div class="field form-group">
        <%= f.label :description, "description:"%>
        <%= f.text_area :description, class: "form-control form-width", rows:"3" %>
      </div>

      <div class="field form-group">
        <%= f.label :in_stock, "in_stock"%>
        <%= f.check_box :in_stock%>
      </div>

      <div class="actions button-margin">
        <%= f.submit "post" , class: "btn btn-success" %>
      </div>
  <% end %>
</div>

app/views/products/_product.html.erb
<div class="col-sm-4 col-lg-4 col-md-4">
  <div class="thumbnail">
    <%= link_to image_tag(product.photo_url(:thumb), alt: 'Photo'), product_path(product) %>
    <hr>
    <div class="caption">
      <h4 class="pull-right"><%= number_to_currency(product.price) %></h4>
      <h4 class="product_show_title"><%= link_to product.title, product_path(product) %>
      </h4>
      <p><%= product.description %></p>
    </div>
    <div class="ratings">
      <p class="pull-right"><%= pluralize(product.reviews.published.count, 'review') %> </p>
      <p>
        <%= show_stars(product) %>
      </p>
    </div>
  </div>
</div>

app/views/products/edit.html.erb
<%= render 'form' %>

app/views/products/index.html.erb
<div class="col-md-9">
  <% if @products.blank? %>
   <h1>No results for you</h1>
  <% else %>
    <%= render @products %>
  <% end %>
</div>
<%= will_paginate @products %>

app/views/products/new.html.erb
<%= render 'form' %>

app/views/products/show.html.erb
      <div class="container">
        <div class="col-md-3">
          <div class="product col-md-12 service-image-left">
            <center>
              <div id="main-photo"><%= image_tag @product.photo_url %></div>
            </center>
          </div>
        </div>
        <div class="col-md-4">
          <div class="product-title"><%= @product.title %></div>
          <div class="product-rating"><i class="fa fa-star gold"></i>
            <i class="fa fa-star gold"></i>
            <i class="fa fa-star gold"></i>
            <i class="fa fa-star gold"></i>
            <i class="fa fa-star-o"></i> </div>
          <hr>
          <div class="product-price">$<%= @product.price %></div><br>
          <%= show_stars(@product) %>
          <% if @product.in_stock? %>
            <div class="product-stock">In Stock</div>
          <% else %>
              <div class="product-not-avalible">Not available</div>
          <% end %>
          <hr>
          <div class="btn-group cart">
              <%= button_to 'Add to cart', add_to_cart_product_path(@product), class: 'btn btn-success' %>
          </div><br><br>
          <div class="btn-group add_review">
           <%= link_to 'Add review', new_review_path(product_id: @product), class:'glyphicon glyphicon-plus' %>
          </div>
        </div>
      </div>
    <div class="container-fluid">
      <div class="col-md-12 product-info">
        <ul id="myTab" class="nav nav-tabs nav_tabs">
          <li class="active" id="description" ><%= link_to 'Description', product_path(@product), remote: true %></a></li>
          <li id="features" ><%= link_to 'Features', features_path(product_id: @product), remote: true %></li>
          <li id="reviews" ><%= link_to 'Reviews', reviews_path(product_id: @product), remote: true %></li>
        </ul>
        <div id="myTabContent" class="tab-content">
          <div class="tab-pane fade in active" id="service-one">

            <section class="container product-info  info">
              <table>
                <tr><th><%= @product.description %></th></tr>
              </table>
            </section>
          </div>
          <div class="tab-pane fade" id="service-two">
            <section class="container">
            </section>
          </div>
          </div>
        </div>
        <hr>
      </div>
      <div class="container-fluid">
        <% if @product_ass.length > 0 %>
        <h3>Related products:</h3>
            <% if @product_ass.previous_page %>
                <%= link_to "< Previous", params.permit(:page).merge(page: @product_ass.previous_page ) %>
            <% end %>
            <% if @product_ass.next_page %>
                <%= sanitize link_to "Next >", params.permit(:page).merge(page: @product_ass.next_page ) %>
            <% end %>
          <div class="col-md-12 product-info">
            <% @product_ass.each do |t| %>
                <% @product_as = Product.find(t) %>
                <%= render 'related_products/related_product' %>
            <% end %>
        <% end %>
        </div>
      </div>

app/views/products/show.js.erb
$('#myTab').find('.active').removeClass('active');
$('#myTab').find('#description').addClass('active');
$('.info').find('table').remove();
$('.info').append("<%= j render 'products/desctiption' %>");