config/routes.rb
Rails.application.routes.draw do
  resources :search_suggestions
  resources :orders do
    member do
      get 'delete_cart_product'
    end
  end
  post 'orders/put_quantity', to: 'orders#put_quantity'

  devise_for :admin_users, ActiveAdmin::Devise.config
  resources :reviews
  ActiveAdmin.routes(self)
  resources :feature_values
  resources :features
  root to: 'products#index'
  resources :categories
  resources :products do
    member do
      post 'add_to_cart'
    end
  end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  validates :title, presence: true, length: { maximum: 40 },
            uniqueness: true
  has_ancestry
  #has_ancestry orphan_strategy: :rootify
  has_many :products, dependent: :destroy

end

app/models/feature.rb
class Feature < ApplicationRecord
  has_many :feature_values, dependent: :destroy
  has_many :products, through: :feature_values

  validates :title, presence: true, length: { maximum: 40 },
            uniqueness: true
end

app/models/feature_value.rb
class FeatureValue < ApplicationRecord
  belongs_to :feature
  belongs_to :product

  validates :title, presence: true, length: { maximum: 40 }
  validates :product_id, presence: true
  validates :feature_id, presence: true
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_products, dependent: :destroy
  enum status_keys: {
      'Processing' => 0,
      'Shipped' => 1,
      'Received' => 2
  }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
            format: { with: VALID_EMAIL_REGEX }
  validates :name, presence: true, length: { maximum: 40 }
  validates :phone, presence: true, length: { maximum: 11 }

  def place(products, order_id)
    products = eval(products)
    products.each do |p|
      OrderProduct.create(product_id: p[:product_id], order_id: order_id,
                          actual_price: Product.find(p[:product_id]).price, quantity: p[:quantity])
    end
  end

  def total_price(order)
    @price = 0
    OrderProduct.where(order_id: order.id).each do |f|
      @price += f.actual_price * f.quantity
    end
    @price
  end
end

app/models/order_product.rb
class OrderProduct < ApplicationRecord
  belongs_to :product
  belongs_to :order
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  has_many :feature_values, dependent: :destroy
  accepts_nested_attributes_for :feature_values, allow_destroy: true
  has_many :features, through: :feature_values
  has_many :reviews, dependent: :destroy
  has_many :related_products
  accepts_nested_attributes_for :related_products, allow_destroy: true
  has_many :related_products_associated, class_name: 'RelatedProduct', foreign_key: 'associated_id'
  has_many :order_products


  validates :title, presence: true, uniqueness: true, length: { maximum: 80 }
  validates :price, presence: true
  validates :photo, presence: true

  scope :by_created, -> { order("created_at DESC") }

  mount_uploader :photo, ProductPhotoUploader
end

app/models/related_product.rb
class RelatedProduct < ApplicationRecord
  belongs_to :product
  belongs_to :associated, class_name: 'Product', foreign_key: 'associated_id'
  validates :product_id, presence: true
  validates :associated_id, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :product
  RATING = [1, 2, 3, 4, 5]
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :author, presence: true, length: { maximum: 40 }
  validates :body, presence: true, length: { maximum: 400 }
  validates :email, presence: true, length: { maximum: 255 },
            format: { with: VALID_EMAIL_REGEX }
  validates :product_id, presence: true

  scope :published, -> { where(published: true) }

end

app/models/search_suggestion.rb
class SearchSuggestion < ApplicationRecord

  def self.terms_for(prefix)
    suggestions = where('term LIKE ?', "#{prefix}_%")
    suggestions.order('popularity desc').limit(10).pluck(:term)
  end

  def self.index_products
    Product.all.each do |product|
      index_term(product.title)
      product.title.split.each { |t| index_term(t) }
    end
  end

  def self.index_term(term)
    where(term: term.downcase).first_or_create.tap do |suggestion|
      suggestion.increment! :popularity
    end
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  def index
  end

  def new
    @order = Order.new
  end

  def create
    @order = Order.create(order_params)
    respond_to do |format|
      if @order.save
        format.html do
          products = cookies[:cart]
          @order.place(products, @order.id)
          AdminMailer.order_confirmation(@order).deliver
          CustomerMailer.order_confirmation(@order).deliver
          cookies.delete :cart
          redirect_to root_url,
                      flash:  {notice: "Order created, wait for email"}
        end
      else
        format.html  { render :new }
      end
    end
  end

  def destroy
  end

  def delete_cart_product
    product_id = params[:id]
    products = eval(cookies[:cart])
    products.delete_if { |h| h[:product_id] == product_id }
    cookies[:cart] = products.to_s
    redirect_to :back
  end

  def put_quantity
    products = eval(cookies[:cart])
    products.each do |p|
      q = "quantitys_#{p[:product_id]}".to_sym
      qty = params[:quantity][q][:qty]
      p[:quantity] = qty
    end
    cookies[:cart] = products.to_s
    redirect_to new_order_path
  end


  private

  def order_params
    params.require(:order).permit(:name, :phone,
                                  :email, :status)
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_product_id , only: [:new, :index, :create]

  def index
    @reviews = @product.reviews.all
  end

  def new
    @review = @product.reviews.new(product_id: params[:product_id])
  end

  def create
    @review = Review.create(review_params)
    respond_to do |format|
    if @review.save
      format.html do
        redirect_to product_path(@product),
                    flash: {notice: "Review created, wait for submitting by admitistrator"}
      end
    else
      format.html  { render :new }
    end
      end
    end

  private

  def review_params
    params.require(:review).permit(:author, :product_id,
                                    :body, :rating, :email)
  end

  def set_product_id
    @product = Product.find(params[:product_id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/feature_values_helper.rb
module FeatureValuesHelper
end

app/helpers/features_helper.rb
module FeaturesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
  
  def show_stars(product)
    average_rating = product.reviews.published.any? ? product.reviews.published.average(:rating) * 20 : 0

    raw("<div class='star-ratings-sprite'>" +
        "<span style='width: #{average_rating.to_i}%' class='star-ratings-sprite-rating'>" +
        "</span>" +
        "</div>")
  end
  
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shop</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <%= link_to 'Guitar Heaven', root_path, class: "navbar-brand" %>
      </div>
      <div class="search">
        <%= form_tag products_path, method: 'get' do %>
          <p>
            <%= text_field_tag :search, params[:search] %>
            <%= submit_tag 'Search', :name  => nil %>
          </p>
        <% end %>
      </div>
      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="cart">
        <span ><%= link_to 'Cart ', orders_path, class:'glyphicon glyphicon-shopping-cart' %>
        (<%= cookies[:cart].present? ? eval(cookies[:cart]).length : 0 %>)</span>
      </div>
    </div>
  </nav>
  <div class="container">
    <div class="row">
      <div class="col-md-3">
        <div class="list-group">
          <table >
          <% Category.all.each do |category| %>
            <tr>
              <td class="category_table"><%= link_to category.title, category_path(category) if category.root? %></td>
            </tr>
          <% end %>
            </table>
        </div>
      </div>
      <p class="messages">
        <span class="notice"><%= notice %></span>
        <span class="alert"><%= alert %></span></p>
      <%= yield %>
    </div>
  </div>

  </body>
  <div class="container" >
    <footer >
      <hr>
      <div class="row">
        <div class="col-lg-12" >
          <p>Copyright &copy; My Website 2016</p>
        </div>
      </div>
    </footer>
  </div>
</html>